### ISSUE TITLE
Adding a ForeignKey

### ISSUE THREAD

**Issue by mansonul** [barseghyanartur/django-fobi#146]
Hi,

How can I add an extra ForeignKey to fobi?

I have a task app and I would like to allow the user that created a task to be able to add some forms to that task.
Should I make an app like you did for Django CMS, DRF, etc? Is this the way to go? And if so, what should include in my models besides the 'expected_fields' in the 'IntegrationProcessor'.
Where should I look for custom views to fit my needs. Should I stick with FBV or it's possible to switch to CBV?
I'm working on a plain Django 1.11 install.

Thank you!

**Comment by barseghyanartur** [comment]
@mansonul:

Look, it depends very much on the issue you're working on.

CMS integrations (FeinCMS, DjangoCMS, Mezzanine) are in my opinion a good example of how to indeed add an extra foreign key to Fobi, because there we add a Fobi as a foreign key to a Django model (page or plugin model) and on certain actions process the actions (POST, GET).

If that's all you need, I would suggest to take a look at how it's done for FeinCMS (since that's the most pure Django-like implementation).

If that doesn't work for you, you should override the default views.

In general, there's no difference between FBV and CBV. You could use both as long as you mimic the functionality. I would stick to FBV though, since that way it would be easier to keep up with updates.

However, some time this year, there will be a switch from FBV to CBV. You could migrate then.

So, as a recap:

- Take a look at FeinCMS integration first and try to make something like that working for you, since that's the most easy solution.
- If that doesn't work, make your custom FBV view.

**Comment by barseghyanartur** [comment]
I'm closing this. Feel free to comment.
