### ISSUE TITLE
securing file uploads

### ISSUE THREAD

**Issue by matacino** [barseghyanartur/django-fobi#279]
Hi,

I have a fobi-form where people upload personal documents.
The formular handler only has a Mail-Handler so actually nothing needs to be saved on the server.
I am experiencing the case that all the uploaded documents are accessible via the internet under the django folder for the uploaded media (eg.: "/media/fobi_plugins/file/")

Is there a configurable way to disable the saving of the uploaded files without interfering with other django apps or at least hide them?

1. I tried "FILE_UPLOAD_TEMP_DIR" in settings.py witch seams not to be used in fobi.
2. `FOBI_PLUGIN_FIELDS_FILE_FILES_UPLOAD_DIR value to the desired (relative) path` is only relative to "/media"

Do I miss an option?

Thnx in advance

matacino

**Comment by matacino** [comment]
hmm. Do I have to develop a separate file-upload element?

**Comment by barseghyanartur** [comment]
Look, there are multiple ways of doing this. It's not really a fobi specific thing. It's standard Django - media directory is served statically. You do need to know the exact file path in order to get the file, but there are ways to secure the uploads. For instance, you could store them on S3 bucket and only make accessible from within your web site. You can also protect your media directory (do not serve it statically, but rather stream uploads via your web site. For that you might need to extend existing or create a new form handler component. Further, use your imagination. :)
