### ISSUE TITLE
Use in CustomFormSets?

### ISSUE THREAD

**Issue by jonhairston** [barseghyanartur/django-fobi#28]
Thanks for the hard work! This is exactly what I am needing. 
However I need some assistance with one thing.
Is there a way to use the fobi in a custom InlineFormSet?

I have a form that will have two parts, the default fields, and the custom fields by fobi.
The default fields will be saved in a separate model from the fields created by fobi. 
Any ideas on how to go about this?

**Comment by barseghyanartur** [comment]
@jonhairston:

If I understand you correctly:

1. You want to create default fields (that you have defined on beforehand) for each form created with `django-fobi`.
2. You want to have these fields defined in a different model (thus, not use the standard `django-fobi` field definition table. Likely, you want to have them saved as a reference to some template so that when you change the originals, all the forms that do make use of them change accordingly. Is that correct?

About the implementation - currently it's not possible. However, my vision of how could you implement/achieve what you need would be the following.

a. Form model should get a checkbox "super". All forms marked as "super" should possibly become extendable.
b. You create super forms.
c. The form model should be extended with `super_form` field which would be a foreign key to an existing `django-fobi` super-form.

Further rendering and validation it's trivial. You would have to save the form definitions in the same model thought, but that's how you could make `django-fobi` work for your needs.

**Comment by jonhairston** [comment]
@barseghyanartur:

Not quite, the default fields come a separate form and model than the fobi model. They are displayed in the same form element in the template though. 

Something like this:

```html 
<form>
    {{ default_form_rendered_here }} 
   {{ fobi_extra_fields_rendered_here }} 
   <input type='submit' /> 
</form>
```

So when the user clicks save, the view the form is contained in should save the default fields to its own model, and fobi will save its fields in its own model.

**Comment by barseghyanartur** [comment]
Ah, it should be very simple then. You should either write a custom form handler or a form callback. django-fobi own fields would be saved anyway. Handling of your own fields should happen in the form handler or form callback. See the docs first.

**Comment by jonhairston** [comment]
You are correct. The custom form handler turned out to be what I needed!
